server:
  listen: "0.0.0.0:8080"

routing:
  default_engine: "main"
  facade:
    docling:
      enabled: true
      prefix: "/v1"
    external:
      enabled: false

engines:
  main:
    enable: true
    compat_type: "docling"
    url: "http://docling-serve:5001"
    api_key_env: "DOCLING_API_KEY"
